<a href="https://colab.research.google.com/github/Eve113/AnalisisDeDatosEPR1/blob/main/python_data_science_epr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Python para Data Science**
A continuación se podrá observar algunos desafíos hechos en el aula de alura del curso *Python Data Science Primeros Pasos*

## **Primeros** **Pasos**

Imprime la frase "Escuela de Datos de Alura"

In [ ]:
print("Escuela de Datos de Alura")

Escuela de Datos de Alura


Imprime tu nombre y apellido

In [ ]:
nombre = "Evelyn"
Apellido = "Pareja Ríos"
print(f'Nombre:{nombre}\nApellido: {Apellido}')

Nombre:Evelyn
Apellido: Pareja Ríos


Imprime tu primer nombre letra por letra. Por ejemplo, si mi nombre es Álvaro, la salida sería:

Á
L
V
A
R
O

In [ ]:
nombre = input("Ingrese su nombre:")
for char in nombre:
  print(char)

Ingrese su nombre:Evelyn
E
v
e
l
y
n


Imprime tu fecha de nacimiento en formato día mes año. Recuerda que los valores de día y año no deben estar entre comillas. Suponiendo una fecha de cumpleaños el 28 de febrero de 2003, el formato debe ser como el siguiente:

28 febrero 2003

In [ ]:
from datetime import datetime

nombre = input("Ingrese su nombre:")
Nacimiento = input("Ingrese su fecha de nacimiento en formato DD/MM/AAAA:")

try:
  fecha_nac = datetime.strptime(Nacimiento, "%d/%m/%Y")
#Condicional para validar si la fecha ingresada es valida
  if fecha_nac > datetime.now():
    print("La fecha no puede ser en el futuro")
  else:
    dia = fecha_nac.strftime("%A")
# Traducir días y meses al español
    if dia == "Monday":
      dia = "Lunes"
    if dia == "Tuesday":
      dia = "Martes"
    if dia == "Wednesday":
      dia = "Miércoles"
    if dia == "Thursday":
      dia = "Jueves"
    if dia == "Friday":
      dia = "Viernes"
    if dia == "Saturday":
      dia = "Sábado"
    if dia == "Sunday":
      dia = "Domingo"
    if fecha_nac.month == 1:
      mes = "enero"
    if fecha_nac.month == 2:
      mes = "febrero"
    if fecha_nac.month == 3:
      mes = "marzo"
    if fecha_nac.month == 4:
      mes = "abril"
    if fecha_nac.month == 5:
      mes = "mayo"
    if fecha_nac.month == 6:
      mes = "junio"
    if fecha_nac.month == 7:
      mes = "julio"
    if fecha_nac.month == 8:
      mes = "agosto"
    if fecha_nac.month == 9:
      mes = "septiembre"
    if fecha_nac.month == 10:
      mes = "octubre"
    if fecha_nac.month == 11:
      mes = "noviembre"
    if fecha_nac.month == 12:
      mes = "diciembre"
  print(f'Hola {nombre}, tu naciste el {fecha_nac.strftime(f"%d de {mes} de %Y un día {dia}")}')

#Condicional para validar si el formato de la fecha es valido
except ValueError:
  print("Formato de fecha incorrecto. Intente nuevamente.")

Ingrese su nombre:Evelyn
Ingrese su fecha de nacimiento en formato DD/MM/AAAA:13/01/2003
Hola Evelyn, tu naciste el: 13 de enero de 2003 un día Lunes


En una empresa de venta de bienes raíces, debes crear un código que analice los datos de ventas anuales para ayudar a la dirección en la toma de decisiones. El código debe recopilar los datos de cantidad de ventas durante los años 2022 y 2023 y calcular la variación porcentual. A partir del valor de la variación, se deben proporcionar las siguientes sugerencias:

Para una variación superior al 20%: bonificación para el equipo de ventas.
Para una variación entre el 2% y el 20%: pequeña bonificación para el equipo de ventas.
Para una variación entre el 2% y el -10%: planificación de políticas de incentivo a las ventas.
Para bonificaciones inferiores al -10%: recorte de gastos.

In [ ]:
año_nuevo= int(input('Ingrese la cantidad de ventas del año actual:'))
año_viejo = int(input('Ingrese la cantidad de ventas del año pasado:'))

if año_viejo == 0:
  print("Las ventas aumentaron respecto al año anterior, en el cual no se registraron ingresos, por lo tanto no se calcula la variación porcentual.")
else:
  variacion = ((año_nuevo - año_viejo)/año_viejo)*100
  if variacion > 20:
    print('Se le dará una bonificación al equipo de ventas')
  elif variacion >= 2 and variacion <= 20:
    print('Se le dará una pequeña bonificación para el equipo de ventas')
  elif variacion >= -10 and variacion < 2:
    print('Se hará una planificación de políticas de incentivo a las ventas')
  else:
    print('Se hará un recorte de gastos')

Ingrese la cantidad de ventas del año actual:12
Ingrese la cantidad de ventas del año pasado:0
Las ventas aumentaron respecto al año anterior, en el cual no se registraron ingresos, por lo tanto no se calcula la variación porcentual.


En una elección para la gerencia de una empresa con 20 empleados, hay cuatro candidatos. Escribe un programa que calcule al ganador de la elección. La votación se realizó de la siguiente manera:

Cada empleado votó por uno de los cuatro candidatos (representados por los números 1, 2, 3 y 4).

También se contaron los votos nulos (representados por el número 5) y los votos en blanco (representados por el número 6).

Al final de la votación, el programa debe mostrar el número total de votos para cada candidato, los votos nulos y los votos en blanco. Además, debe calcular y mostrar el porcentaje de votos nulos con respecto al total de votos y el porcentaje de votos en blanco con respecto al total de votos.

In [ ]:
candidato1 = 0
candidato2 = 0
candidato3 = 0
candidato4 = 0
nulos = 0
blanco = 0
for i in range(0, 20):
    voto = int(input('Ingresa tu voto: '))
    if voto == 1:
        candidato1 += 1
    elif voto == 2:
        candidato2 += 1
    elif voto == 3:
        candidato3 += 1
    elif voto == 4:
        candidato4 += 1
    elif voto == 6:
        blanco += 1
    else:
        nulos += 1
        print("Voto anulado debido a que se marco un numero distinto de 1,2,3,4 y 6")


print(f'Votos candidato 1: {candidato1}')
print(f'Votos candidato 2: {candidato2}')
print(f'Votos candidato 3: {candidato3}')
print(f'Votos candidato 4: {candidato4}')
print(f'Votos nulos: {nulos}')
print(f'Votos en blanco: {blanco}')
print(f'Porcentaje de votos nulos: {(nulos / 20 * 100)}')
print(f'Porcentaje de votos en blanco: {(blanco / 20 * 100)}')

Ingresa tu voto: 1
Ingresa tu voto: 2
Ingresa tu voto: 3
Ingresa tu voto: 4
Ingresa tu voto: 5
Voto anulado debido a que se marco un numero distinto de 1,2,3,4 y 6
Ingresa tu voto: 4
Ingresa tu voto: 3
Ingresa tu voto: 4
Ingresa tu voto: 5
Voto anulado debido a que se marco un numero distinto de 1,2,3,4 y 6
Ingresa tu voto: 6
Ingresa tu voto: 7
Voto anulado debido a que se marco un numero distinto de 1,2,3,4 y 6
Ingresa tu voto: 3
Ingresa tu voto: 4
Ingresa tu voto: 6
Ingresa tu voto: 2
Ingresa tu voto: 3
Ingresa tu voto: 5
Voto anulado debido a que se marco un numero distinto de 1,2,3,4 y 6
Ingresa tu voto: 6
Ingresa tu voto: 4
Ingresa tu voto: 4
Votos candidato 1: 1
Votos candidato 2: 2
Votos candidato 3: 4
Votos candidato 4: 6
Votos nulos: 4
Votos en blanco: 3
Porcentaje de votos nulos: 20.0
Porcentaje de votos en blanco: 15.0


Escribe un código que lee la lista siguiente y realiza:

In [ ]:
lista = [16, 14, 63, 65, 17, 99, 70, 11, 20, 48, 79, 32, 17, 89, 12, 25, 66]
# 1. Leer el tamaño de la lista
# 2. Leer el valor máximo y mínimo
# 3. Calcular la suma de los valores de la lista
# 4. Mostrar un mensaje al final: La lista tiene `tamano` números, donde el mayor
# es `mayor` y el menor es `menor`. La suma de los valores es `suma`.


tamaño = len(lista)
mayor = max(lista)
menor = min(lista)
suma = sum(lista)

print(f'La lista tiene {tamaño} números, donde el mayor es {mayor} y el menor es {menor}. La suma de los valores es {suma}.')

La lista tiene 17 números, donde el mayor es 99 y el menor es 11. La suma de los valores es 743.


Escribe una función que genere la tabla de multiplicar de un número entero del 1 al 10, según la elección del usuario. Como ejemplo, para el número 7, la tabla de multiplicar se debe mostrar en el siguiente formato:

In [ ]:
import math

def tabla(numero):
  for i in range(1,11):
    if numero <= 10:
      print(f'{numero} x {i} = {numero * i}')
    else:
      print("El número ingresado es mayor a 10")
      break

numero = int(input('ingrese un número:'))
tabla(numero)


ingrese un número:11
El número ingresado es mayor a 10


Crea una función que lea la siguiente lista y devuelva una nueva lista con los múltiplos de 3:

In [ ]:
import math

def multiplos(lista):
  lista_nv = []
  for i in lista:
    if i % 3 == 0:
      lista_nv.append(i)
  return lista_nv

lista = [97, 80, 94, 88, 80, 1, 16, 53, 62, 32, 24, 99]
multiplos(lista)



[24, 99]

Crea una lista de los cuadrados de los números de la siguiente lista [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]. Recuerda utilizar las funciones lambda y map() para calcular el cuadrado de cada elemento de la lista

In [ ]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
cuadrados = map(lambda x: x**2, lista)
print(list(cuadrados))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


Has sido contratado como científica de datos de una asociación de skate. Para analizar las notas recibidas por los skaters en algunas competiciones a lo largo del año, necesitas crear un código que calcule la puntuación de los atletas. Para ello, tu código debe recibir 5 notas ingresadas por los jueces

In [ ]:
lista = []
jueces = int(input('Ingrese la cantidad de jueces:'))
n = jueces + 1
for i in range(1,n):
  nota = float(input('Ingrese la calificación del jurado:'))
  lista.append(nota)
puntuación = sum(lista) - min(lista) - max(lista)
print(f'La puntuación del competidor es: {puntuación},\nBaja el número {max(lista)} y el número {min(lista)}')


Ingrese la cantidad de jueces:3
Ingrese la calificación del jurado:1
Ingrese la calificación del jurado:3
Ingrese la calificación del jurado:2
La puntuación del competidor es: 2.0,
Baja el número 3.0 y el número 1.0


Para cumplir con una demanda de una institución educativa para el análisis del rendimiento de sus estudiantes, necesitas crear una función que reciba una lista de 4 notas y devuelva:

In [ ]:
import numpy as np
from statistics import mean

def estudiante(lista):
  for i in range(1,5):
    nota = float(input('Ingrese una nota:'))
    lista.append(nota)
  if sum(lista) / len(lista) >= 3:
    situación = 'aprobado'
  else:
    situación = 'reprobado'
  print(f'La mayor nota del curso fue de {max(lista)}, la menor nota fue de {min(lista)}, la media es de {mean(lista)}, la situación del estudiante es de {situación}')

lista = []
estudiante(lista)

Ingrese una nota:1
Ingrese una nota:2
Ingrese una nota:5
Ingrese una nota:2
La mayor nota del curso fue de 5.0, la menor nota fue de 1.0, la media es de 2.5, la situación del estudiante es de reprobado


## **Manipulación y análisis con NumPy y Pandas**


### **Primera practica en clase**

Cargar la Dataset del enlace https://gist.githubusercontent.com/ahcamachod/41b8a65c5e5b58125401deafb68af460/raw/f84320f69efa1cc3e86e1db054422cfa4869c63e/manzanas.csv

In [ ]:
import numpy as np
url = 'https://gist.githubusercontent.com/ahcamachod/41b8a65c5e5b58125401deafb68af460/raw/f84320f69efa1cc3e86e1db054422cfa4869c63e/manzanas.csv'
datos = np.loadtxt(url,delimiter=',', usecols= np.arange(1,88,1))

array([[  1.2013,   2.2013,   3.2013,   4.2013,   5.2013,   6.2013,
          7.2013,   8.2013,   9.2013,  10.2013,  11.2013,  12.2013,
          1.2014,   2.2014,   3.2014,   4.2014,   5.2014,   6.2014,
          7.2014,   8.2014,   9.2014,  10.2014,  11.2014,  12.2014,
          1.2015,   2.2015,   3.2015,   4.2015,   5.2015,   6.2015,
          7.2015,   8.2015,   9.2015,  10.2015,  11.2015,  12.2015,
          1.2016,   2.2016,   3.2016,   4.2016,   5.2016,   6.2016,
          7.2016,   8.2016,   9.2016,  10.2016,  11.2016,  12.2016,
          1.2017,   2.2017,   3.2017,   4.2017,   5.2017,   6.2017,
          7.2017,   8.2017,   9.2017,  10.2017,  11.2017,  12.2017,
          1.2018,   2.2018,   3.2018,   4.2018,   5.2018,   6.2018,
          7.2018,   8.2018,   9.2018,  10.2018,  11.2018,  12.2018,
          1.2019,   2.2019,   3.2019,   4.2019,   5.2019,   6.2019,
          7.2019,   8.2019,   9.2019,  10.2019,  11.2019,  12.2019,
          1.202 ,   2.202 ,   3.202 ],
       [ 

In [ ]:
# Cantidad de dimenciones del Array
datos.ndim

2

In [ ]:
# Forma del Array
datos.shape

(6, 87)

In [ ]:
# Convertir las columnas en filas y las filas en columnas
Datos_Transpuestos = datos.T

array([[  1.2013,  79.72  ,  42.67  ,  62.55  ,  48.26  ,  71.25  ],
       [  2.2013,  81.08  ,  44.37  ,  62.73  ,  51.01  ,  71.35  ],
       [  3.2013,  79.68  ,  44.73  ,  63.43  ,  50.91  ,  70.9   ],
       [  4.2013,  79.8   ,  46.75  ,  63.83  ,  53.94  ,  71.92  ],
       [  5.2013,  80.63  ,      nan,  66.06  ,  61.27  ,  72.91  ],
       [  6.2013,  80.8   ,  51.59  ,  69.22  ,  65.44  ,  74.39  ],
       [  7.2013,  80.28  ,  57.8   ,  72.07  ,  56.51  ,  73.1   ],
       [  8.2013,  78.99  ,  62.14  ,  69.31  ,  53.    ,  70.24  ],
       [  9.2013,  76.77  ,  56.76  ,  65.18  ,  43.87  ,  69.12  ],
       [ 10.2013,  76.09  ,  50.85  ,  62.13  ,  42.12  ,  68.98  ],
       [ 11.2013,  76.36  ,  46.43  ,  64.17  ,  43.98  ,  68.58  ],
       [ 12.2013,  77.16  ,  46.73  ,  65.5   ,  44.66  ,  69.5   ],
       [  1.2014,  77.5   ,  45.85  ,  66.85  ,  47.73  ,  70.14  ],
       [  2.2014,  79.03  ,  49.25  ,  68.38  ,  52.31  ,  70.58  ],
       [  3.2014,  80.28  ,  48.14

### Visualización y selección

In [ ]:
fechas = Datos_Transpuestos[:,0]
fechas

### Tratamiento de Nan

In [ ]:
np.mean(Kaliningrado)

### **Ejercicio propuesto en clase**
Un colega te pidió que cargues una base de datos y verifiques el número de filas y columnas del archivo cargado. Tenía dudas sobre si se habían cargado todas las filas.

¿Cómo determinar las dimensiones correctas de una matriz?

Para responder a esta pregunta, necesitarás acceder al siguiente dataset. Puedes usar la opción skiprows=1 para omitir la primera línea del archivo.

In [ ]:
url = 'https://raw.githubusercontent.com/allanspadini/numpy/dados/bytebank.csv'
import numpy as np
datos = np.loadtxt(url, delimiter = ',',skiprows=1, dtype=float)
datos.shape

(12, 2)

### **Nuevo dataset**

In [ ]:
url = 'https://gist.githubusercontent.com/ahcamachod/9be09de793dc3bf1e6c3d98eb4e5b1ef/raw/21b85572693200040e11284ef6dcfc3457ec8e11/citrus.csv'
import numpy as np
np.loadtxt(url, delimiter = ',', usecols = np.arange(1, 6, 1), skiprows = 1 )


array([[  2.96,  86.76, 172.  ,  85.  ,   2.  ],
       [  3.91,  88.05, 166.  ,  78.  ,   3.  ],
       [  4.42,  95.17, 156.  ,  81.  ,   2.  ],
       ...,
       [ 15.59, 256.5 , 168.  ,  82.  ,  20.  ],
       [ 15.92, 260.14, 142.  ,  72.  ,  11.  ],
       [ 16.45, 261.51, 152.  ,  74.  ,   2.  ]])